# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.docsign.com:
    container_name: orderer.docsign.com
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      - ORDERER_GENERAL_LOGLEVEL=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganizations/docsign.com/orderers/orderer.docsign.com/msp:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/docsign.com/orderers/orderer.docsign.com/tls/:/var/hyperledger/orderer/tls
    - orderer.docsign.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.mainorg.docsign.com:
    container_name: peer0.mainorg.docsign.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.mainorg.docsign.com
      - CORE_PEER_ADDRESS=peer0.mainorg.docsign.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.mainorg.docsign.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.mainorg.docsign.com:7051
      - CORE_PEER_LOCALMSPID=MainOrgMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/mainorg.docsign.com/peers/peer0.mainorg.docsign.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/mainorg.docsign.com/peers/peer0.mainorg.docsign.com/tls:/etc/hyperledger/fabric/tls
        - peer0.mainorg.docsign.com:/var/hyperledger/production
    ports:
      - 7051:7051
      - 7053:7053

  peer1.mainorg.docsign.com:
    container_name: peer1.mainorg.docsign.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.mainorg.docsign.com
      - CORE_PEER_ADDRESS=peer1.mainorg.docsign.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.mainorg.docsign.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.mainorg.docsign.com:7051
      - CORE_PEER_LOCALMSPID=MainOrgMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/mainorg.docsign.com/peers/peer1.mainorg.docsign.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/mainorg.docsign.com/peers/peer1.mainorg.docsign.com/tls:/etc/hyperledger/fabric/tls
        - peer1.mainorg.docsign.com:/var/hyperledger/production

    ports:
      - 8051:7051
      - 8053:7053

  # peer0.org2.docsign.com:
  #   container_name: peer0.org2.docsign.com
  #   extends:
  #     file: peer-base.yaml
  #     service: peer-base
  #   environment:
  #     - CORE_PEER_ID=peer0.org2.docsign.com
  #     - CORE_PEER_ADDRESS=peer0.org2.docsign.com:7051
  #     - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.docsign.com:7051
  #     - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org2.docsign.com:7051
  #     - CORE_PEER_LOCALMSPID=Org2MSP
  #   volumes:
  #       - /var/run/:/host/var/run/
  #       - ../crypto-config/peerOrganizations/org2.docsign.com/peers/peer0.org2.docsign.com/msp:/etc/hyperledger/fabric/msp
  #       - ../crypto-config/peerOrganizations/org2.docsign.com/peers/peer0.org2.docsign.com/tls:/etc/hyperledger/fabric/tls
  #       - peer0.org2.docsign.com:/var/hyperledger/production
  #   ports:
  #     - 9051:7051
  #     - 9053:7053

  # peer1.org2.docsign.com:
  #   container_name: peer1.org2.docsign.com
  #   extends:
  #     file: peer-base.yaml
  #     service: peer-base
  #   environment:
  #     - CORE_PEER_ID=peer1.org2.docsign.com
  #     - CORE_PEER_ADDRESS=peer1.org2.docsign.com:7051
  #     - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org2.docsign.com:7051
  #     - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.docsign.com:7051
  #     - CORE_PEER_LOCALMSPID=Org2MSP
  #   volumes:
  #       - /var/run/:/host/var/run/
  #       - ../crypto-config/peerOrganizations/org2.docsign.com/peers/peer1.org2.docsign.com/msp:/etc/hyperledger/fabric/msp
  #       - ../crypto-config/peerOrganizations/org2.docsign.com/peers/peer1.org2.docsign.com/tls:/etc/hyperledger/fabric/tls
  #       - peer1.org2.docsign.com:/var/hyperledger/production
  #   ports:
  #     - 10051:7051
  #     - 10053:7053
